class Settings():
    ROWS_COUNT = 5
    COLS_COUNT = 5

    MIN_ROW_INDEX = 0
    MAX_ROW_INDEX = ROWS_COUNT - 1
    MIN_COL_INDEX = 0
    MAX_COL_INDEX = COLS_COUNT - 1

    CELL_SIZE = 128
    PIXEL_HEIGHT = ROWS_COUNT * CELL_SIZE
    PIXEL_WIDTH = COLS_COUNT * CELL_SIZE

    FPS = 60